export const WEBSITE_LIST_SUCCESS = "WEBSITE_LIST_SUCCESS";
export const WEBSITE_LIST_FAIL = "WEBSITE_LIST_FAIL"; 

export const WEBSITE_DETAILS_REQUEST = "WEBSITE_DETAILS_REQUEST";
export const WEBSITE_DETAILS_SUCCESS = "WEBSITE_DETAILS_SUCCESS";
export const WEBSITE_DETAILS_FAIL = "WEBSITE_DETAILS_FAIL"; 